version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    # interval: weekly
    # day: saturday
  commit-message:
    prefix: "chore(deps):"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    # interval: weekly
    # day: saturday
  commit-message:
    prefix: "chore(deps):"
