version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  commit-message:
    prefix: "chore(deps):"
  open-pull-requests-limit: 20
  reviewers:
    - "arznaar"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  commit-message:
    prefix: "fix(deps):"
  open-pull-requests-limit: 20
  reviewers:
    - "arznaar"
