version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
#     interval: daily
    interval: weekly
    day: saturday
  commit-message:
    prefix: "chore(deps):"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
#     interval: daily
    interval: weekly
    day: saturday
  commit-message:
    prefix: "chore(deps):"
  open-pull-requests-limit: 20
