on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

concurrency: publish

jobs:
  publish:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/github-script@v5
        if: ${{ github.event_name == 'pull_request' }}
        id: has_pending_automerge
        with:
          script: |
            const { owner, repo } = context.repo;
            const pulls = await github.rest.pulls.list({ owner, repo, state: 'open' }).then((x) => x.data);
            return pulls.some((x) => x.auto_merge !== null);
      - uses: actions/setup-node@v2.5.1
        if: ${{ github.event_name != 'pull_request' || steps.has_pending_automerge.outputs.result != 'true' }}
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
        if: ${{ github.event_name != 'pull_request' || steps.has_pending_automerge.outputs.result != 'true' }}
      - run: npm run publish
        if: ${{ github.event_name != 'pull_request' || steps.has_pending_automerge.outputs.result != 'true' }}
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
