on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-integration:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run test
  lint-commits:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run ci:lint-commits
        env:
          COMMITS_NUMBER: ${{ github.event.pull_request.commits }}
  analyze:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - run: npm ci
    - run: npm run ci:build

    - uses: github/codeql-action/analyze@v1
