on: [pull_request]

jobs:
  test-integration:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn test
  lint-commits:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn ci:lint-commits
        env:
          COMMITS_NUMBER: ${{ github.event.pull_request.commits }}
  analyze:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
    - uses: actions/checkout@v2.3.3

    - uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - run: yarn --frozen-lockfile
    - run: yarn run ci:build

    - uses: github/codeql-action/analyze@v1
