on:
  # pull_request:
  #   # types: [ closed ]
  #   branches:
  #     - develop
  workflow_dispatch

jobs:
  trigger_on_merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            console.log("before rest1");
            const pulls = await github.pulls.list({ owner, repo, state: 'open' }).then((x) => x.data);
            console.log(pulls);
            const openAutoMergePrs = pulls.some((x) => x.auto_merge !== null);
            console.log({ openAutoMergePrs });
            if (openAutoMergePrs) { return; }
            github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: '.github/workflows/publish.yml',
              ref: 'refs/heads/develop',
            });
